# Generated by Django 4.0 on 2022-10-17 16:13

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=5.0, max_digits=10)),
                ('count', models.PositiveIntegerField(default=0)),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Date of Birth')),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default='Other', max_length=20)),
                ('occupation', models.CharField(blank=True, max_length=200)),
                ('address', models.CharField(blank=True, max_length=250)),
                ('btc_wallet', models.CharField(blank=True, max_length=100, verbose_name='Bitcoin Address')),
                ('eth_wallet', models.CharField(blank=True, max_length=100, verbose_name='Ethereum Address')),
                ('trx_wallet', models.CharField(blank=True, max_length=100, verbose_name='Tron Address')),
                ('code', models.CharField(blank=True, max_length=13, unique=True, verbose_name='Referral Code')),
                ('country', django_countries.fields.CountryField(blank=True, default='US', max_length=2)),
                ('profile_pics', models.ImageField(blank=True, null=True, upload_to='image')),
                ('city', models.CharField(default='New York', help_text='Change to your city', max_length=100)),
                ('postal_code', models.PositiveIntegerField(blank=True, null=True, verbose_name='City Postal Code')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profiles',
            },
        ),
    ]
