# Generated by Django 4.0 on 2022-10-18 03:03

from django.db import migrations, models
import django_countries.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('pkid', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('trx', models.CharField(blank=True, max_length=10, verbose_name='Transaction Id')),
                ('payment', models.CharField(choices=[('Bitcoin Address', 'Bitcoin Address'), ('Ethereum Address', 'Ethereum Address'), ('Tron Address', 'Tron Address')], default='Bitcoin Address', max_length=30, verbose_name='Payment Method')),
                ('proof', models.ImageField(blank=True, upload_to='')),
                ('wallet_address', models.CharField(blank=True, max_length=100, verbose_name='Receiving Wallet Address')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Enter Amount in Usd Ratio', max_digits=8)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Processing', 'Processing'), ('Successful', 'Successful')], default='Pending', max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('pkid', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('trxid', models.CharField(blank=True, max_length=10)),
                ('investment_type', models.CharField(blank=True, choices=[('Basic', 'Basic Plan'), ('Limited', 'Limited Plan'), ('Unlimited', 'Unlimited Plan'), ('Individual Retirement Account', 'Individual Retirement Account Plan')], max_length=30, verbose_name='Investment Type')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=8)),
                ('percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('total_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('total_days', models.PositiveIntegerField(blank=True, null=True)),
                ('profit', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Processing', 'Processing'), ('Successful', 'Successful')], default='Pending', max_length=20)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('completed', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InvestmentTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('investment_type', models.CharField(blank=True, choices=[('Basic', 'Basic Plan'), ('Limited', 'Limited Plan'), ('Unlimited', 'Unlimited Plan'), ('Individual Retirement Account', 'Individual Retirement Account Plan')], max_length=30, verbose_name='Investment Type')),
            ],
            options={
                'verbose_name': 'Investment Type',
                'verbose_name_plural': 'Investment Types',
            },
        ),
        migrations.CreateModel(
            name='PaidBy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='Preferred Name')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Amount Paid')),
                ('country', django_countries.fields.CountryField(blank=True, default='US', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('pkid', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('balance', models.DecimalField(decimal_places=2, default=5.0, max_digits=10)),
                ('count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Withdrawal',
            fields=[
                ('pkid', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('trx', models.CharField(blank=True, max_length=10, verbose_name='Transaction Id')),
                ('payment', models.CharField(choices=[('Bitcoin Address', 'Bitcoin Address'), ('Ethereum Address', 'Ethereum Address'), ('Tron Address', 'Tron Address')], default=False, max_length=30, verbose_name='Payment Method')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Enter Amount in Usd Ratio', max_digits=8)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Processing', 'Processing'), ('Successful', 'Successful')], default='Pending', max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
