# Generated by Django 4.0 on 2022-10-19 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='withdrawal',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='Enter Amount in Usd Ratio', max_digits=10),
        ),
    ]
