# Generated by Django 4.0 on 2022-10-20 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('investment', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investment',
            name='percentage',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=3),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='investment',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='investment', to='users.user'),
        ),
    ]
