# Generated by Django 4.0 on 2022-10-19 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0003_deposit_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawal',
            name='slug',
            field=models.SlugField(blank=True, max_length=8),
        ),
    ]
