# Generated by Django 4.0 on 2022-10-20 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0003_alter_investment_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investmenttypes',
            name='investment_type',
            field=models.CharField(blank=True, max_length=30, verbose_name='Investment Type'),
        ),
    ]
