# Generated by Django 4.0 on 2022-10-19 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0003_alter_withdrawal_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='withdrawal',
            name='slug',
            field=models.SlugField(blank=True, max_length=15),
        ),
    ]
