# Generated by Django 4.0 on 2022-10-20 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0003_alter_investment_percentage_alter_investment_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investment',
            name='percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
        ),
    ]
