# Generated by Django 4.0 on 2022-10-20 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('investment', '0004_alter_investment_percentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investment',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='investment', to='users.user'),
            preserve_default=False,
        ),
    ]
