# Generated by Django 4.0 on 2022-10-20 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0004_alter_investmenttypes_investment_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investment',
            name='investment_type',
            field=models.CharField(blank=True, choices=[('Basic', 'Basic Plan'), ('Limited', 'Limited Plan'), ('Unlimited', 'Unlimited Plan'), ('Individual Retirement Account', 'Individual Retirement Account Plan')], max_length=30, verbose_name='Investment Type'),
        ),
        migrations.DeleteModel(
            name='InvestmentTypes',
        ),
    ]
